######################################################################
# Automatically generated by qmake (3.0) Fri Jul 1 15:01:38 2016
######################################################################

TEMPLATE = app
TARGET = qml-dynamic-create-elements
INCLUDEPATH += .

QT += qml quick
CONFIG += c++11

# Input
SOURCES += main.cpp
RESOURCES += qml.qrc
